### ISSUE TITLE
Not dumping voice messages

### ISSUE THREAD

**Issue by Lohoris** [tvdstaaij/telegram-history-dump#12]
This isn't dumping the voice messages… is there an option somewhere I didn't notice, or it this feature missing?

```
  download_media:
    photo: true
    document: true
    audio: true
    video: true
```

Pictures are downloaded fine.

```
{"event":"message","unread":false,"id":69985,"flags":258,"media":{"type":"???"}
```
